"""
Curated Pega Knowledge Base — Phase 22 (Database, XML/JSON, Upgrade, and Pega-Specific Exceptions)
Covers: SQL exceptions, XML/JSON parse errors, upgrade errors, rule resolution errors,
        flow/assignment exceptions, connector exceptions, clipboard exceptions.

Run: python -m crawler.seed_kb_phase22
"""

import json, logging
from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from config import RAW_DOCS_DIR

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

CURATED_DOCS_PHASE22 = [
    {
        "url": "curated://pega-database-sql-exceptions",
        "title": "Database and SQL Exceptions in Pega — Connection, Query, Deadlock, and Schema Errors",
        "content": """# Database and SQL Exceptions in Pega — Complete Reference

## Connection Exceptions

### java.sql.SQLException: Cannot get a connection, pool error
- **What**: Database connection pool exhausted — all connections are in use
- **Cause**: Slow queries holding connections, connection leak, pool size too small, burst of concurrent requests
- **Fix**:
  1. Check SMA → Database → Connection Pool → active/max/waiting counts
  2. Increase max pool size in prconfig.xml: `<env name="database/pool/maxActive" value="100"/>`
  3. Find and fix slow queries (PEGA0002 alerts)
  4. Check for connection leaks in custom Java code (always close ResultSets and Statements)

### java.sql.SQLException: Connection refused / Connection timed out
- **What**: Can't connect to the database server
- **Cause**: DB server down, wrong host/port, firewall blocking, network issue
- **Fix**: Test DB connectivity from Pega server. Check DB server status. Verify connection string. Check firewall rules.

### java.sql.SQLException: ORA-12541: TNS:no listener (Oracle)
- **What**: Oracle TNS listener is not running
- **Fix**: Start the Oracle listener: `lsnrctl start`. Check listener.ora configuration.

### java.sql.SQLException: ORA-01017: invalid username/password
- **What**: Database credentials are wrong
- **Fix**: Verify username/password in prconfig.xml or JNDI data source. Check if password expired.

## Query Exceptions

### java.sql.SQLSyntaxErrorException: Invalid SQL
- **What**: The SQL generated by Pega is syntactically invalid
- **Common causes**: Property name contains special characters, missing column in database, version-specific SQL syntax
- **Fix**: Check the SQL in PegaRULES log or Tracer. Verify the table/column exists. Run the SQL manually to identify the syntax issue.

### java.sql.SQLDataException: Data too long for column
- **What**: Trying to insert/update a value that exceeds the column length
- **Cause**: Property value longer than the database column allows (e.g., 500-char string in a VARCHAR(255) column)
- **Fix**: Increase column length. Truncate the value before saving. Add validation to limit input length.

### java.sql.SQLIntegrityConstraintViolationException
- **What**: Unique constraint, foreign key, or not-null constraint violated
- **Common causes**: Duplicate key (inserting a case with an existing ID), missing required field, orphaned reference
- **Fix**: Check the constraint being violated. Ensure unique values for primary keys. Populate required fields.

### java.sql.SQLTimeoutException: Query timeout
- **What**: Database query exceeded the configured timeout
- **Fix**: Optimize the query (add indexes, reduce result set). Increase timeout for batch operations. Check PEGA0002 alerts.

## Deadlock Exceptions

### java.sql.SQLException: Deadlock detected / ORA-00060 / Error 1205
- **What**: Two transactions are blocking each other — database killed one to resolve
- **Common cause**: Concurrent updates to the same case, batch + interactive conflicts, poorly ordered operations
- **Fix**:
  1. Implement retry logic: catch the deadlock exception, wait briefly, retry
  2. Ensure consistent operation ordering across all code paths
  3. Reduce transaction duration (commit sooner)
  4. Use optimistic locking where possible
  5. Check the database deadlock graph to identify the two competing transactions

## Schema Exceptions

### java.sql.SQLException: Table or view does not exist
- **What**: Pega is trying to access a table that doesn't exist in the database
- **Cause**: Schema not generated, table dropped, wrong database schema prefix
- **Fix**: Run Pega's DDL generation tool. Verify the class-to-table mapping. Check the database schema.

### java.sql.SQLException: Column not found
- **What**: Query references a column that doesn't exist in the table
- **Cause**: Declare Index not applied, property added but schema not updated, property renamed
- **Fix**: Run schema update from Dev Studio → System → Database → Columns. Verify Declare Index rules.

## Database-Specific Errors
| Database | Error | Meaning | Fix |
|----------|-------|---------|-----|
| Oracle | ORA-00001 | Unique constraint violated | Check for duplicate keys |
| Oracle | ORA-00054 | Resource busy (table locked) | Wait or kill blocking session |
| Oracle | ORA-01555 | Snapshot too old | Increase undo retention |
| Oracle | ORA-04031 | Shared pool memory exhausted | Increase shared_pool_size |
| PostgreSQL | ERROR 23505 | Unique violation | Check for duplicate keys |
| PostgreSQL | ERROR 40001 | Serialization failure | Retry the transaction |
| PostgreSQL | ERROR 53300 | Too many connections | Increase max_connections |
| SQL Server | Error 1205 | Deadlock victim | Implement retry logic |
| SQL Server | Error 8645 | Memory grant timeout | Optimize query, add memory |
| SQL Server | Error 9002 | Transaction log full | Back up or expand log |
"""
    },
    {
        "url": "curated://pega-xml-json-parse-exceptions",
        "title": "XML and JSON Parse Exceptions in Pega — Parsing Errors, Malformed Data, and Mapping Failures",
        "content": """# XML and JSON Parse Exceptions in Pega

## XML Parse Exceptions

### org.xml.sax.SAXParseException: Content is not allowed in prolog
- **What**: XML data has invalid characters before the XML declaration
- **Cause**: BOM (Byte Order Mark), whitespace, or non-XML content before `<?xml ...?>`
- **Fix**: Strip BOM/whitespace from the input. Ensure the source sends clean XML.

### org.xml.sax.SAXParseException: Premature end of file
- **What**: XML document is incomplete or truncated
- **Cause**: Network timeout during transfer, buffer overflow, partial response from external system
- **Fix**: Check connector timeout settings. Verify the full response is received. Check Content-Length header.

### org.xml.sax.SAXParseException: The element type must be terminated
- **What**: XML tag is not properly closed
- **Cause**: Malformed XML from external system (missing closing tag, mismatched tags)
- **Fix**: Validate the XML externally. Contact the source system to fix their XML generation.

### javax.xml.bind.UnmarshalException: Unexpected element
- **What**: XML structure doesn't match the expected schema
- **Cause**: External system changed their XML format, wrong WSDL version, namespace mismatch
- **Fix**: Update WSDL/XSD. Re-import the WSDL in the SOAP connector. Check namespaces.

### Pega Parse Rule XML Mapping Errors
- **Message**: `Error mapping XML element [element] to property [property]`
- **Cause**: XML structure changed, element renamed, element moved to different level
- **Fix**: Update the Parse XML rule to match the current XML structure. Test with a sample response.

## JSON Parse Exceptions

### com.fasterxml.jackson.core.JsonParseException: Unexpected character
- **What**: JSON is malformed (invalid syntax)
- **Cause**: Extra comma, missing quote, HTML returned instead of JSON (like a login page), non-JSON content
- **Fix**: Validate the JSON externally (jsonlint.com). Check if the endpoint is returning an error page instead of JSON.

### com.fasterxml.jackson.databind.JsonMappingException: Cannot deserialize
- **What**: JSON value type doesn't match the expected type
- **Cause**: Property expects a number but JSON has a string, or expects an object but gets an array
- **Fix**: Check the JSON structure. Update the Parse JSON mapping. Handle type conversions.

### JSON Response is Empty or Null
- **Message**: `NullPointerException when parsing JSON response` or `Empty response body`
- **Cause**: External system returned empty body (HTTP 204), error with empty response, content-type header mismatch
- **Fix**: Check HTTP status code before parsing. Handle empty responses gracefully. Verify Content-Type header.

### JSON Array vs Object Confusion
- **Message**: `Expected object but got array` or `Expected array but got object`
- **Cause**: API sometimes returns an array, sometimes a single object. Parse rule expects one format.
- **Fix**: Handle both cases in the parse mapping. Use conditional logic to detect array vs object.

## Common Parse Debugging Steps
1. **Capture the raw response**: Enable response logging on the connector (temporarily in non-prod)
2. **Validate externally**: Paste the response into an XML/JSON validator
3. **Check the parse rule**: Does the mapping match the actual structure?
4. **Check encoding**: UTF-8 vs other encodings can cause parsing failures
5. **Check for HTML error pages**: If the API returns a login page or error page, the parser gets invalid input
6. **Use Tracer**: Enable Connector and Parse Rule tracking to see the raw data and mapping steps
"""
    },
    {
        "url": "curated://pega-upgrade-migration-exceptions",
        "title": "Pega Upgrade and Migration Exceptions — Common Errors During Version Upgrades",
        "content": """# Pega Upgrade and Migration Exceptions — Complete Reference

## Pre-Upgrade Exceptions

### Schema Compatibility Error
- **Message**: `Schema version mismatch: current [X], required [Y]`
- **Cause**: Database schema is not at the correct version for the target Pega version
- **Fix**: Run the schema upgrade DDL scripts in order. Never skip schema versions.

### Dependency Check Failure
- **Message**: `Missing required ruleset: [ruleset-name] version [X.Y]`
- **Cause**: The target version requires rulesets that aren't installed
- **Fix**: Install prerequisite rulesets before upgrading. Check the upgrade guide for dependencies.

## During-Upgrade Exceptions

### Rule Merge Conflict
- **Message**: `Merge conflict detected in rule [rule-name] — manual resolution required`
- **Cause**: Customized rule conflicts with a Pega-delivered update
- **Fix**: Review the merge conflict. Choose to keep your version, take Pega's version, or manually merge. Document all merge decisions.

### DDL Execution Failure
- **Message**: `ALTER TABLE failed: column already exists` or `CREATE INDEX failed`
- **Cause**: Partial upgrade left schema in intermediate state, manual schema modifications
- **Fix**: Check which DDL scripts have been applied. Apply remaining scripts manually. Never modify Pega tables outside of the upgrade process.

### Import Failure During Upgrade
- **Message**: `Failed to import rules archive: [archive-name]`
- **Cause**: Corrupted archive, version dependency issue, disk space shortage
- **Fix**: Re-download the upgrade media. Verify disk space. Check import log for specific errors.

### ClassCastException During Upgrade
- **Message**: `ClassCastException during rule conversion`
- **Cause**: Rule format changed between versions, custom code incompatible with new internals
- **Fix**: Check the upgrade release notes for breaking changes. Update custom code to match new APIs.

## Post-Upgrade Exceptions

### Rule Resolution Failure After Upgrade
- **Message**: `Cannot find rule [rule-name] in version [X.Y]`
- **Cause**: Rule was deprecated/removed in the new version, ruleset version not updated in access group
- **Fix**: Check the deprecation guide. Update access groups to reference new ruleset versions. Replace deprecated rules.

### Guardrail Score Degradation
- **Message**: `Guardrail score dropped from [X] to [Y] after upgrade`
- **Cause**: New guardrail checks in the upgraded version flagging existing patterns
- **Fix**: Review new guardrail violations. Prioritize and fix them. Some may be informational only.

### UI Rendering Errors After Upgrade
- **Message**: `Section rendering error`, `JavaScript error in console`
- **Cause**: Deprecated UI APIs, Classic UI features removed in Constellation, CSS changes
- **Fix**: Test all UI screens after upgrade. Update deprecated section patterns. Migrate to Constellation if applicable.

### Agent/Queue Processor Failures After Upgrade
- **Message**: Agent errors referencing old class names or methods
- **Cause**: Internal API changes in the new version
- **Fix**: Review agent activities for deprecated method calls. Update to use current APIs.

## Upgrade Best Practices
1. **Always run pre-upgrade assessment** (Dev Studio → Upgrade → Pre-Upgrade Assessment)
2. **Back up the database and file system** before upgrading
3. **Test in non-production first** — complete the upgrade in dev, then QA, then staging, then production
4. **Document all merge decisions** — you'll need to repeat them in each environment
5. **Run post-upgrade validation** — test all critical flows, integrations, and reports
6. **Check deprecated features list** — plan migration before upgrading
7. **Monitor alerts closely** after upgrade — watch for new alert patterns
"""
    },
    {
        "url": "curated://pega-rule-resolution-flow-exceptions",
        "title": "Rule Resolution and Flow Exceptions in Pega — Missing Rules, Flow Errors, and Assignment Failures",
        "content": """# Rule Resolution and Flow Exceptions in Pega

## Rule Resolution Exceptions

### PRRuntimeException: Rule not found
- **Message**: `Cannot find rule [RuleType] [ClassName].[RuleName]`
- **Common causes**:
  - Rule doesn't exist in any ruleset version
  - Rule exists but not in the user's access group rulesets
  - Rule is checked out (locked) and not available
  - Ruleset version is locked/read-only and rule hasn't been promoted
- **Fix**: Verify the rule exists (search in Dev Studio). Check access group rulesets include the rule's ruleset. Check if the rule is checked out.

### PRRuntimeException: Multiple rules found (ambiguous)
- **Message**: `Ambiguous rule resolution — multiple candidates for [rule-name]`
- **Cause**: Multiple rules with the same name at the same specificity level, circumstancing conflict
- **Fix**: Check for duplicate rules. Review circumstancing. Use rule resolution tool: Dev Studio → Tools → Rule Resolution.

### PRRuntimeException: Circular rule reference
- **Message**: `Circular rule reference detected: [rule-A] → [rule-B] → [rule-A]`
- **Cause**: Two rules reference each other, creating an infinite loop during resolution
- **Fix**: Break the circular dependency. Restructure the rules to avoid mutual references.

## Flow Exceptions

### FlowException: No assignment target
- **Message**: `Cannot create assignment — no operator or workbasket specified for [shape-name]`
- **Cause**: Routing rule returned no valid target, workbasket doesn't exist, operator is disabled
- **Fix**: Check the routing rule or router activity. Verify the target operator/workbasket exists and is active.

### FlowException: Invalid transition
- **Message**: `No valid transition from [shape-A] to [shape-B]`
- **Cause**: Flow connector missing between shapes, condition on connector evaluates to false with no alternative path
- **Fix**: Check flow diagram for missing connectors. Add an "Otherwise" connector for decision shapes.

### FlowException: SLA configuration error
- **Message**: `SLA rule [sla-name] not found or misconfigured`
- **Cause**: SLA referenced in the flow doesn't exist, wrong class/name, SLA has invalid time settings
- **Fix**: Verify SLA rule exists and is in the correct class. Check urgency/deadline/goal time values.

### FlowException: Subprocess error
- **Message**: `Error executing subprocess [flow-name] in [shape-name]`
- **Cause**: Sub-flow has an error, sub-flow is missing, parameters not properly passed
- **Fix**: Test the sub-flow independently. Check parameter mapping. Verify the sub-flow exists.

## Assignment Exceptions

### AssignmentException: Worklist full
- **Message**: `Cannot assign to operator [operator-id] — worklist limit exceeded`
- **Cause**: Operator has too many open assignments (configurable limit)
- **Fix**: Increase worklist limit. Reassign some cases. Review workload distribution.

### AssignmentException: Work object locked
- **Message**: `Cannot assign — work object [case-id] is locked by [other-user]`
- **Cause**: Another user or process has the case open/locked
- **Fix**: Wait for the lock to release. Check SMA for lock holders. Force-release stale locks.

### AssignmentException: Routing failed
- **Message**: `Router [router-name] returned no valid operator`
- **Cause**: All operators in the workbasket are disabled, skill-based routing found no matching operator
- **Fix**: Check workbasket members. Verify operator skills match routing criteria. Add a fallback routing rule.

## Clipboard Exceptions

### ClipboardException: Page already exists
- **Message**: `Cannot create page [page-name] — it already exists on the clipboard`
- **Fix**: Use `Page-Remove` before re-creating. Or use `obj-Open` to update the existing page.

### ClipboardException: Property type mismatch
- **Message**: `Cannot set [property-name] — expected [type-A] but got [type-B]`
- **Fix**: Check property definition. Ensure the value matches the property type (text/integer/date/page).

### ClipboardException: Read-only property
- **Message**: `Cannot modify read-only property [property-name]`
- **Cause**: Trying to set an auto-populated (.px) property or a declared property
- **Fix**: Don't try to set auto-populated properties. For declared properties, modify the inputs instead.
"""
    },
    {
        "url": "curated://pega-connector-service-exceptions",
        "title": "Connector and Service Exceptions in Pega — REST, SOAP, JMS, and File Integration Errors",
        "content": """# Connector and Service Exceptions — Complete Reference

## REST Connector Exceptions

### ConnectorException: HTTP 400 Bad Request
- **What**: The external service rejected the request as invalid
- **Common cause**: Missing required field, wrong data type, invalid JSON/XML format
- **Fix**: Check the request body in Tracer. Validate against the API documentation. Test with Postman.

### ConnectorException: HTTP 401 Unauthorized
- **What**: Authentication credentials invalid or missing
- **Common cause**: Expired token, wrong API key, OAuth token not refreshed
- **Fix**: Check auth profile. Refresh OAuth token. Verify API key is correct and active.

### ConnectorException: HTTP 403 Forbidden
- **What**: Authenticated but not authorized for this resource
- **Common cause**: IP not whitelisted, insufficient OAuth scope, API plan limit reached
- **Fix**: Check IP whitelist at the API provider. Request additional OAuth scopes. Check API usage limits.

### ConnectorException: HTTP 404 Not Found
- **What**: The requested resource doesn't exist at the specified URL
- **Common cause**: Wrong endpoint URL, resource deleted, API version changed
- **Fix**: Verify the URL. Check API documentation for correct endpoint. Check if API version changed (v1 → v2).

### ConnectorException: HTTP 429 Too Many Requests
- **What**: Rate limit exceeded at the external API
- **Fix**: Implement rate limiting in Pega. Add retry with exponential backoff. Cache responses in data pages.

### ConnectorException: HTTP 500/502/503/504
- **What**: External server error
- **Fix**: This is the external system's problem. Implement retry logic. Use circuit breaker pattern. Alert the external team.

## SOAP Connector Exceptions

### SOAPFaultException
- **Message**: SOAP fault with faultcode and faultstring from the external service
- **Fix**: Read the faultstring for the error description. Check the SOAP request envelope. Validate against the WSDL.

### WSDLException: WSDL Parse Error
- **What**: Can't parse the WSDL to generate the connector
- **Cause**: Invalid WSDL, WSDL URL unreachable, authentication required for WSDL
- **Fix**: Download WSDL manually and import as a file. Validate the WSDL with an XML tool.

### SOAPMessageCreationException
- **What**: Can't create the SOAP request message
- **Cause**: Mapping error, required SOAP header missing, namespace mismatch
- **Fix**: Check the request mapping in the SOAP connector. Verify namespace URIs. Check required headers.

## JMS/Kafka Connector Exceptions

### JMSException: Connection to broker failed
- **What**: Can't connect to the JMS broker (ActiveMQ, IBM MQ, etc.)
- **Fix**: Check broker URL. Verify queue/topic exists. Check authentication. Test with JMS client tool.

### JMSException: Queue/Topic not found
- **What**: The specified queue or topic doesn't exist on the broker
- **Fix**: Create the queue/topic on the broker. Verify the exact name (case-sensitive).

### KafkaException: Topic not available
- **What**: Kafka topic doesn't exist or is not reachable
- **Fix**: Create the topic. Check broker connectivity. Verify topic permissions.

## File Connector Exceptions

### FileNotFoundException: Source file not found
- **What**: The specified file path doesn't exist
- **Fix**: Check the file path. Verify the file listener directory. Check file permissions.

### IOException: Permission denied
- **What**: Pega process doesn't have read/write permission to the file or directory
- **Fix**: Check OS file permissions. Ensure the Pega user has read/write access to the directory.

### IOException: Disk full
- **What**: No space left on the file system
- **Fix**: Free disk space. Archive old files. Increase disk capacity.

## Service Exceptions (Inbound)

### ServiceException: Invalid request format
- **What**: Incoming request to Pega's Service REST/SOAP doesn't match expected format
- **Fix**: Check the service rule's request mapping. Validate the incoming request against the API contract.

### ServiceException: Authentication required
- **What**: Incoming service call doesn't include proper authentication
- **Fix**: Check the service authentication profile. Verify the caller is sending the correct auth headers.

### ServiceException: Rate limit exceeded
- **What**: Too many incoming requests to the Pega service
- **Fix**: Implement rate limiting on the service. Scale Pega nodes. Add caching layer (CDN/API gateway).

## General Connector Debugging Steps
1. **Check Tracer** → enable Connector tracking → see request/response
2. **Check PegaRULES log** for the full exception with HTTP status and response body
3. **Test independently** with Postman, curl, or SOAP UI
4. **Check network** → can Pega server reach the endpoint? (ping, telnet, curl)
5. **Check authentication** → tokens expired? credentials correct?
6. **Check mapping** → request data transform producing correct output?
7. **Check timeout** → is the connector waiting too long?
"""
    },
]


def seed_phase22():
    RAW_DOCS_DIR.mkdir(parents=True, exist_ok=True)
    count = 0
    for doc in CURATED_DOCS_PHASE22:
        slug = doc["title"].lower().replace(" ", "_").replace("/", "_").replace("—", "-").replace("'", "").replace(",", "").replace(".", "")[:80]
        filename = f"phase22_{slug}.json"
        filepath = RAW_DOCS_DIR / filename
        payload = {"url": doc["url"], "title": doc["title"], "content": doc["content"].strip()}
        filepath.write_text(json.dumps(payload, indent=2), encoding="utf-8")
        count += 1
        logger.info(f"[{count}/{len(CURATED_DOCS_PHASE22)}] Saved: {doc['title']}")
    logger.info(f"\nPhase 22 complete — {count} documents saved to {RAW_DOCS_DIR}")

if __name__ == "__main__":
    seed_phase22()
